# Generated by Django 5.2.7 on 2025-10-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recuperation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='municipalite',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Municipalite',
        ),
    ]
