# Generated by Django 5.2.7 on 2025-10-21 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recuperation', '0002_alter_coordonnee_municipalite_delete_municipalite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissement',
            old_name='code',
            new_name='codeImm',
        ),
        migrations.AddField(
            model_name='etablissement',
            name='codeOrg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='ide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Recuperation.ide'),
        ),
    ]
