# Generated by Django 5.2.7 on 2025-10-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recuperation', '0003_rename_code_etablissement_codeimm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='site',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='telephone',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
