# Generated by Django 5.2.7 on 2025-10-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recuperation', '0004_alter_coordonnee_site_alter_coordonnee_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coordonnee',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
