# Generated by Django 5.2.7 on 2025-10-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recuperation', '0005_alter_coordonnee_site_alter_coordonnee_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etablissement',
            old_name='professionel',
            new_name='professionnel',
        ),
    ]
