# Generated by Django 5.2.7 on 2025-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recuperation', '0006_rename_professionel_etablissement_professionnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordonnee',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='adulte',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='prescolaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='primaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='professionnel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='secondaire',
            field=models.BooleanField(default=False),
        ),
    ]
