# Generated by Django 5.2.7 on 2025-10-19 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IMSE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indice', models.FloatField()),
                ('rang', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipalite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.IntegerField()),
                ('Nom', models.CharField(max_length=100)),
                ('Statut', models.CharField(max_length=1)),
                ('Region_administrative', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SFR',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indice', models.FloatField()),
                ('rang', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IDE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('defavorisation', models.BooleanField()),
                ('imse', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Recuperation.imse')),
                ('sfr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Recuperation.sfr')),
            ],
        ),
        migrations.CreateModel(
            name='Coordonnee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adresse', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=7)),
                ('site', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=12)),
                ('municipalite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recuperation.municipalite')),
            ],
        ),
        migrations.CreateModel(
            name='Regroupement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('nom_court', models.CharField(max_length=50)),
                ('superficie', models.IntegerField()),
                ('perimetre', models.IntegerField()),
                ('langue', models.CharField(max_length=3)),
                ('coordonnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recuperation.coordonnee')),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('prescolaire', models.BooleanField()),
                ('primaire', models.BooleanField()),
                ('secondaire', models.BooleanField()),
                ('professionel', models.BooleanField()),
                ('adulte', models.BooleanField()),
                ('type', models.CharField(max_length=50)),
                ('coordonnee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recuperation.coordonnee')),
                ('ide', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Recuperation.ide')),
                ('regroupement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recuperation.regroupement')),
            ],
        ),
    ]
